### ISSUE TITLE
您好，豆丁的docin文件head 和 page分开的那种docin格式，会解压成swf吗？ 微信 nlanguage

### ISSUE THREAD

**Issue by nissansz** [rty813/doc_downloader#10]
您好，豆丁的docin文件head 和 page分开的那种docin格式，会解压成swf吗？
微信 nlanguage

**Comment by rty813** [comment]
没遇到过你说的这种情况

**Comment by rty813** [comment]
能举个例子么？

**Comment by nissansz** [comment]
看附件









--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: "豆腐" ***@***.***>
 

 
 发送时间: 2021-03-19 10:31:33
 

 
 收件人:rty813/doc_downloader ***@***.***> 

 
 抄送:nissanjp ***@***.***>,Author ***@***.***> 

 
 主题: Re: [rty813/doc_downloader] 您好，豆丁的docin文件head 和 page分开的那种docin格式，会解压成swf吗？ 微信 nlanguage (#10)
 





 能举个例子么？

**Comment by rty813** [comment]
> 看附件
> […](#)
> --------------------------------------------------------------------------------
> ------------------ 原始邮件 ------------------ 发件人: "豆腐" ***@***.***> 发送时间: 2021-03-19 10:31:33 收件人:rty813/doc_downloader ***@***.***> 抄送:nissanjp ***@***.***>,Author ***@***.***> 主题: Re: [rty813/doc_downloader] 您好，豆丁的docin文件head 和 page分开的那种docin格式，会解压成swf吗？ 微信 nlanguage (#10) 能举个例子么？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你在github上回复，不要直接从邮件里面回复，否则我看不到你发的附件
