### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by klk0301** [rty813/doc_downloader#17]
```
请输入网址（输入exit退出）：https://www.doc88.com/p-28761857292280.html

DevTools listening on ws://127.0.0.1:54380/devtools/browser/c41bbe33-bb5c-4220-ad2a-2049ab2a857c
道客巴巴: 《TB10097-2019 铁路房屋建筑设计标准 - 道客巴巴》
Traceback (most recent call last):
  File "docDownloader.py", line 44, in <module>
  File "fire\core.py", line 141, in Fire
  File "fire\core.py", line 466, in _Fire
  File "fire\core.py", line 681, in _CallAndUpdateTrace
  File "docDownloader.py", line 16, in main
  File "doc88.py", line 43, in download
  File "selenium\webdriver\remote\webelement.py", line 80, in click
  File "selenium\webdriver\remote\webelement.py", line 633, in _execute
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="surplus-btn" id="continueButton">...</div> is not clickable at point (439, 9). Other element would receive the click: <a href="javascript:;" title="缩小" id="zoomOutButton">...</a>
  (Session info: chrome=92.0.4515.159)

[28632] Failed to execute script docDownloader
```

**Comment by rty813** [comment]
@klk0301 你可以调试一下看看，是什么元素遮住了“阅读全文”按钮，因为我这个地方是没有问题的：
![image](https://user-images.githubusercontent.com/22488813/130036583-d79a1418-cb78-43eb-bcf3-3b84dddc457c.png)

调试的时候，可以在点击按钮的地方打断点，然后卡住以后，在浏览器的开发者工具里面，看看id为continueButton的元素上面有没有遮盖东西。
![image](https://user-images.githubusercontent.com/22488813/130036615-fb675834-9a97-4772-be53-a1572afae354.png)

**Comment by klk0301** [comment]
> @klk0301 你可以调试一下看看，是什么元素遮住了“阅读全文”按钮，因为我这个地方是没有问题的：
> ![image](https://user-images.githubusercontent.com/22488813/130036583-d79a1418-cb78-43eb-bcf3-3b84dddc457c.png)
> 
> 调试的时候，可以在点击按钮的地方打断点，然后卡住以后，在浏览器的开发者工具里面，看看id为continueButton的元素上面有没有遮盖东西。
> ![image](https://user-images.githubusercontent.com/22488813/130036615-fb675834-9a97-4772-be53-a1572afae354.png)

`    # 获取页数
    try:
        #print("there have readshop")
        num_of_pages = driver.find_element_by_id('readshop').find_element_by_class_name(
            'mainpart').find_element_by_class_name('shop3').find_element_by_class_name('text').get_attribute('innerHTML')
        num_of_pages = int(num_of_pages.split(' ')[-1])
    except:
        try:
            print("there is no readshop")
            num_of_pages = driver.find_element_by_id('toolbar').find_element_by_class_name(
                'mainpart').find_element_by_id('item-page-panel').find_element_by_class_name('text').get_attribute('innerHTML')
            num_of_pages = int(num_of_pages.split(' ')[-1])
        except:
            print("there is no toolbar")
        finally:
            pass
    finally:
        pass`
我修改了部分代码，因为我这里出现了 找不到 readshop的情况，通过读取 toolbar元素中的页数 解决了

**Comment by klk0301** [comment]
刚才又出现找不到 button的问题，原因是我的笔记本电脑分辨率低 1366×768  chrome窗口打开之后，刚好看不到continuebutton，所以会报错，请问这时候怎么才能够解决?
