### ISSUE TITLE
没法用了吗？

### ISSUE THREAD

**Issue by xuanweiace** [rty813/doc_downloader#18]

**Comment by xuanweiace** [comment]
试了豆丁和原创力，都不行

**Comment by rty813** [comment]
发一下文档链接

**Comment by xuanweiace** [comment]
https://max.book118.com/html/2017/1109/139498756.shtm


![image](https://user-images.githubusercontent.com/35798588/132129749-b2b40f0a-4af6-46c1-9f11-e0f84eaccbe1.png)

**Comment by rty813** [comment]
这个是由于原创力的网站发生了一些变化，导致旧的脚本无法解析。目前已经更新
