### ISSUE TITLE
原创力，报错

### ISSUE THREAD

**Issue by xuanweiace** [rty813/doc_downloader#20]
文章链接：https://max.book118.com/html/2017/0224/93289210.shtm
![image](https://user-images.githubusercontent.com/35798588/132971336-4d3d09e8-e8c9-4f5a-b695-63c5d5f74035.png)

**Comment by xuanweiace** [comment]
我下载了两次，都在同一个地方报错，麻烦看下，谢谢啦

**Comment by rty813** [comment]
像这种问题，一般是由于网页没有加载出来。可以尝试换一个网络环境，再试试。我这里是ok的
![image](https://user-images.githubusercontent.com/22488813/133194097-24448fa8-2062-424a-a9fb-be6da29881d9.png)
[江苏省内河航道护岸维护工作标准.doc.pdf](https://github.com/rty813/doc_downloader/files/7158826/doc.pdf)
