### ISSUE TITLE
给您更新了doc88.py文件

### ISSUE THREAD

**Issue by sssongq** [rty813/doc_downloader#22]
您好，您的道客巴巴的下载代码应该由于网页格式变了，现在有一点问题，给您修改了一下。
链接：https://pan.baidu.com/s/1nuY2B7ymEVqNQSbooccgNQ 
提取码：fv8c

**Comment by liubaoji505** [comment]
有效，感谢分享

**Comment by rty813** [comment]
> 您好，您的道客巴巴的下载代码应该由于网页格式变了，现在有一点问题，给您修改了一下。
> 链接：https://pan.baidu.com/s/1nuY2B7ymEVqNQSbooccgNQ
> 提取码：fv8c

感谢，建议直接提交PR
