### ISSUE TITLE
win10 64位系统应该下载哪个chromedriver？

### ISSUE THREAD

**Issue by xudong-zhu** [rty813/doc_downloader#30]
![image](https://user-images.githubusercontent.com/53168757/156495214-f7046bce-3ae0-4fe9-81a6-019637558690.png)

**Comment by jikejixiang** [comment]
我看到贴子说都要下win32这个，好像没有win系列64位版本的driver。这个工具你能正常使用么？我遇到程序缺少参数的错误。

**Comment by billeyang** [comment]
win32就可以，本来64位就兼容32位的，关键是得把chrome和chromedriver版本对应起来。
