### ISSUE TITLE
SyntaxError: Non-ASCII character '\xe8' in file docDownloader.py

### ISSUE THREAD

**Issue by anyiblog** [rty813/doc_downloader#4]
项目克隆后，本地运行出错。
Mac系统，Python版本：2.7。
需要的扩展都已经安装了。

python docDownloader.py
  File "docDownloader.py", line 12
SyntaxError: Non-ASCII character '\xe8' in file docDownloader.py on line 12, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

![B88FE2C6-65FB-40DC-A735-BE3BFF5F8D59](https://user-images.githubusercontent.com/26721169/74111683-7c11a280-4bd1-11ea-91e2-3fb20dcc90d9.png)

**Comment by rty813** [comment]
这个是没有指定编码导致的中文错误。可以在所有.py文件的开头都加入 #coding: utf-8
