### ISSUE TITLE
在线的我试了下下载不了

### ISSUE THREAD

**Issue by maliqiang** [rty813/doc_downloader#5]
在线的我试了下下载不了

**Comment by rty813** [comment]
你下载的文档网址是多少？

**Comment by maliqiang** [comment]
> 你下载的文档网址是多少？
https://wenku.baidu.com/view/0f97f52ad1d233d4b14e852458fb770bf78a3bf4.html

**Comment by rty813** [comment]
哦哦。这个是不支持百度文库的

**Comment by rty813** [comment]
支持的文库以readme里面提到的为准

**Comment by iesap** [comment]
请问这个有简单的使用说明么？或者交流qq群啥的？

**Comment by rty813** [comment]
这个就下载下来以后，直接运行docDownloader.exe就可以了。没有qq群，有什么问题可以直接在issue里面提
