### ISSUE TITLE
doc88下载闪退

### ISSUE THREAD

**Issue by phinehasz** [rty813/doc_downloader#7]
下了windows 打包的release 7z, 解压后尝试下载 https://www.doc88.com/p-8116099467414.html
闪退了

**Comment by rty813** [comment]
收到，目前正在排查

**Comment by rty813** [comment]
我试了一下，可以成功下载，你看一下你的报错是什么？

**Comment by jnrel1** [comment]
你是不是发错人了。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rty813/doc_downloader"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月23日(星期五) 下午3:03
收件人:&nbsp;"rty813/doc_downloader"<doc_downloader@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [rty813/doc_downloader] doc88下载闪退 (#7)





 
我试了一下，可以成功下载，你看一下你的报错是什么？

**Comment by rty813** [comment]
> 你是不是发错人了。。。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "rty813/doc_downloader" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月23日(星期五) 下午3:03 收件人:&nbsp;"rty813/doc_downloader"<doc_downloader@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [rty813/doc_downloader] doc88下载闪退 (#7) 我试了一下，可以成功下载，你看一下你的报错是什么？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

应该是你watch了这个仓库，所以Github自动给你发的邮件。我是不会单独给你发邮件的

**Comment by phinehasz** [comment]
> 我试了一下，可以成功下载，你看一下你的报错是什么？
> 你打开控制台（cmd或powershell），然后切换到解压后的程序目录，然后通过输入命令`docDownloader.exe`来进行下载，看看报错是什么。
> 
> 大概率是因为chromedriver版本不匹配导致的。你可以自行下载与你chrome对应版本的chromedriver，替换掉程序目录下的chromedriver

谢谢, 是chrome driver的问题. 
在此处可以下载对应的driver: 
https://chromedriver.chromium.org/downloads

**Comment by phinehasz** [comment]
已经解决, 可以close了, 多谢, 非常好用

**Comment by rty813** [comment]
好的，谢谢支持
