### ISSUE TITLE
豆丁部分链接无法下载

### ISSUE THREAD

**Issue by dstmath** [rty813/doc_downloader#9]
部分豆丁链接下载下来的jpg文件大小为22bytes:
图片里面内容为: file can not read now!
下载链接：　https://www.docin.com/p-1643955256.html

**Comment by rty813** [comment]
正在修复

**Comment by rty813** [comment]
这个问题是由于豆丁网的下载链接发生了变化，增加了一个sid字段。目前已经修复，可以重新拉取最新代码，或下载release中的1.2版本。
